### ISSUE TITLE
[BUG] Mod crash on start on client

### ISSUE THREAD

**Issue by AmibeSkyfy16** [ByMartrixx/player-events#17]
**Describe the bug**

Steps to reproduce the behaviour:
I have intellij Idea, if i uncomment this code:
    PlayerKillEntityCallback.EVENT.register ...
and then run gradle task "fabric:runClient, the game crash
i can only use on my server, but i will be able to have EntityKilledEvent on my client

this is my complete logs: https://pastebin.com/83vDa2ug
see line 144

**Comment by IotaBread** [comment]
The mod/api is only server side, it isn't meant to work on clients
