### ISSUE TITLE
[Enhancement] Add Events for Player Kills, and Entity Kills

### ISSUE THREAD

**Issue by amnotbananaama** [ByMartrixx/player-events#2]
Hi, thank you for creating this mod! Super useful, and prevents me from having to use datapacks or the like. Would it be possible for you to add event(s) for when a player kills another player, and/or when a player kills another entity? Currently detecting this with commands is laggy and fairly messy, and it would be great to have a smoother way to do it. Thanks!

**Comment by IotaBread** [comment]
Thanks for the suggestion! I'm planning to do a refactor of the mod config in the next days, so this feature should be there on the next update. ~~Any suggestion on how it should look on the config file?~~ (Nvm, I was thinking of another feature)
