### ISSUE TITLE
[REQUEST] Add support for MiniMessage (custom colors and styling)

### ISSUE THREAD

**Issue by zachthedev** [ByMartrixx/player-events#23]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Ability to use the cool and nifty features of [minimessage](https://docs.adventure.kyori.net/minimessage/format.html), such as a hover event and the rainbow effect

**Describe alternatives you've considered**
Just living with it as is

**Additional context**
This would be an easy way to remove the `§` character from having to be used when most mods use & or minimessage.

**Comment by IotaBread** [comment]
Since 2.3.0, there's proper support for [Simplified Text Format](https://placeholders.pb4.eu/user/text-format/), which has mostly the same features as minimessage. In theory, this format was in place since 2.0.1, but it didn't work properly (see #25), and I wasn't aware of it
