### ISSUE TITLE
[BUG] StyledChat incompatibility

### ISSUE THREAD

**Issue by arnokeesman** [ByMartrixx/player-events#25]
**Describe the bug**
Formatting cannot be disabled and does not work with [StyledChat](https://github.com/Patbox/StyledChat/).

**To Reproduce**
Case 1:
1. Install PlayerEvents, StyledChat and FabricAPI on a server.
2. Configure PE to start a line with a color and set a [placeholder](https://placeholders.pb4.eu/user/default-placeholders/).
Case 2:
1. Install PlayerEvents, StyledChat and FabricAPI on a server.
2. Configure PE to use [STF](https://placeholders.pb4.eu/user/text-format/) formatting.

**Expected behaviour**
Case 1:
Colored text continues after placeholder.
Case 2:
STF tag works.

**Screenshots**
![image](https://user-images.githubusercontent.com/34793978/172654935-11eaec4f-c92b-46fb-8b9c-e9c36b8f5ab1.png)
![image](https://user-images.githubusercontent.com/34793978/172654830-a1d78405-7d3c-4887-8453-14985049e914.png)

Suggested solution:
Add an option to the config to disable PE formatting.

**Comment by IotaBread** [comment]
Thanks for opening the issue. I suspect this has something to do with how I replace event placeholders within the text. I'll try to solve it once I have time
