### ISSUE TITLE
[BUG] Execution of commands not working

### ISSUE THREAD

**Issue by t0ssox** [ByMartrixx/player-events#26]
**Describe the bug**
When I'm trying to run any command with events, neither works. Using example config provided on README of this GitHub gives me this output in console on join event:
```
[Server thread/INFO]: Welcome t0ssox
[Server thread/INFO]: Unknown or incomplete command, see below for error
[Server thread/INFO]: /say Hello t0ssox<--[HERE]
```
I guess this may have something to do with latest changes of text parsing or 1.19 bring up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install this mod and QSL/Fabric API.
2. Launch server for the first time.
3. Replace default config using example one from README from this GitHub.
4. Restart server.
5. None of these commands are executing for those events.

**Expected behaviour**
Successfully command execution without any error about unknown command in console.

**Comment by IotaBread** [comment]
I'll fix this when I have some time, should be in a couple of days
