### ISSUE TITLE
[REQUEST] 1.19.3 Support

### ISSUE THREAD

**Issue by zachthedev** [ByMartrixx/player-events#28]
Mixin errors when using 1.19.3 fabric server/api versions.
Probably not a huge update, but would be appreciated! Thanks

**Comment by IotaBread** [comment]
I haven't managed to reproduce any mixin errors, could you provide a log file?

**Comment by zachthedev** [comment]
I had version 2.4.1 and updated to 2.4.4 and there are no error logs now.
I would say that it is fixed now and if anyone has this issue, update your mod file.
