### ISSUE TITLE
Trouble importing API

### ISSUE THREAD

**Issue by MerryPlace** [ByMartrixx/player-events#4]
Your api looks amazing but I'm sadly confused on how to use it. 
I added the lines to the `build.gradle`, I added the dependency to the `fabric.mod.json`, I built the api jar and put it in my `run/mods` folder. 
But when I try to use your api in my code I get errors like `PlayerDeathCallback cannot be resolved`.
I'm guessing I have to import something in the java code but I don't know how/what.

Any tips?

**Comment by IotaBread** [comment]
You have to import the PlayerDeathCallback first: `import io.github.bymartrixx.playerevents.api.event.PlayerDeathCallback`. Your IDE should be doing this automatically, if it isn't there probably is a problem with the IDE or the dependency

**Comment by IotaBread** [comment]
Other three things:
1. What do you mean with "built the api jar and put it in my run/mods folder"?
2. If you add the same line you added in the build.gradle, but with `include` instead of `modImplementation`, Loom should bundle the api with your mod, so you don't need to add both to the mods folder
3. Sadly, on May 1st, Bintray is shutting down and my api will stop working if you used the steps in the README. I'm still trying to find an alternative for Bintray

**Comment by MerryPlace** [comment]
~~I already tried adding that import to the file but I get an error `The import io.github cannot be resolved`.~~  Solved this!

1. I assumed that was the point of getting the jar in the [compiling](https://github.com/ByMartrixx/player-events#compiling) section of your tutorial. I see now that was unnecessary. This is my first experience modding minecraft so I'm pretty lost, sorry 😅. 
2. ~~I changed the `modImplementation` line to `include` [see here](https://i.imgur.com/Um3Mmal.png)~~ I realised I still need the `include` som we're good there.
but still without the jar in the mod folder fabric loader gives me a failed to launch error [`You must install version 2.0.0 or later of player_events_api.`](https://i.imgur.com/v1seu41.png). 

3. Sorry to hear that. I'm mainly making this mod for my own personal use over the next month but I do hope you find a long term solution, I can't find other fabric apis like this one. And thank you so much for your quick reply!!!

**Comment by MerryPlace** [comment]
Okay so I'm very happy to report that I am using the api successfully. 
The only issue is I have to remove `"player_events_api": ">=2.0.0"` from `fabric.mod.json` to get it to launch. Otherwise fabric loader still gives me a failed to launch error [`You must install version 2.0.0 or later of player_events_api.`](https://i.imgur.com/v1seu41.png). 

Since I'm using it, it seems weird that it would throw that error. But I suppose this is fine. Thank you for your help!

**Comment by IotaBread** [comment]
> Sorry to hear that. I'm mainly making this mod for my own personal use over the next month
If so, you can download the api jar and use something like this:
```gradle
dependencies {
   // Before
   modImplementation "io.github.bymartrixx.playerevents:player-events-api:2.0.0"

   // After
   modImplementation files("path/to/player-events-api-2.0.0.jar")
}
```

> Thank you for your help!
No problem :)

About the fabric.mod.json part, that is just for defining the mod as a dependency when not using `include`. In your case, you don't need it
