### ISSUE TITLE
bump [REQUEST]

### ISSUE THREAD

**Issue by ghost** [ByMartrixx/player-events#6]
UPDATE TO 1.17 snapshots?

**Comment by IotaBread** [comment]
I tried it earlier today, but I had some issues that were preventing me from testing the mod. I'll try it later

**Comment by IotaBread** [comment]
Btw, does the current jar crash the game/give errors? I think you should be able to use it in snapshots if there are no errors

**Comment by IotaBread** [comment]
I was able to fix the testing issue, so I'm gonna test it tomorrow. In theory, unless there were changes in Minecraft's code, it should work without errors

**Comment by IotaBread** [comment]
Should be working, there weren't any errors

**Comment by ghost** [comment]
on 21w19a dont work:
ain/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onPlayerJoin(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in player_events_api.mixins.json:PlayerJoinMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap player-events-api-refmap.json

**Comment by IotaBread** [comment]
can you send the crash-report or the logs?

**Comment by ghost** [comment]
without this mod server runs fine and without errors .. after installation it crashes at startup
[2021-05-20-6.log.gz](https://github.com/ByMartrixx/player-events/files/6517238/2021-05-20-6.log.gz)

**Comment by IotaBread** [comment]
I'll look into it later today

**Comment by IotaBread** [comment]
Just tested it with just player-events, no errors. I'll see the source of the mods you currently have to check if any of those is causing the problem
[latest.log](https://github.com/ByMartrixx/player-events/files/6519470/latest.log)

**Comment by IotaBread** [comment]
~~Can you send the mod files you have?~~ Nvm, found them

**Comment by IotaBread** [comment]
I can't seem to reproduce this, even replicating exactly which mods you have (except for Flan, I'm using 1.3.2 while you have 1.3.1). I'd try deleting the .fabric and .mixin.out folder, or re-downloading the mods
[latest.log](https://github.com/ByMartrixx/player-events/files/6519709/latest.log)

**Comment by ghost** [comment]
flan 1.3.2 also crashes the server at startup .. i deleted the mixin and fabric folders but the problem still persists both with the flan mod and without the flan mod

**Comment by IotaBread** [comment]
Thats really weird... can you send me your whole mods folder as a zip? I may be able to reproduce the issue that way

**Comment by ghost** [comment]
here is the complete server with your mod crashes without it starts normally

https://mega.nz/file/MTJEhLDJ#hEBzBW52-0dG27OM

if you can help me find where the problem is I would be very grateful

**Comment by ghost** [comment]
on 21w20a same problem :/

**Comment by IotaBread** [comment]
Sorry, I haven't been able to work on this since Thursday. I have managed to reproduce it, so I'm going to check what's going on

**Comment by IotaBread** [comment]
It should work in 2.1.1

**Comment by ghost** [comment]
perfect ;) thx

pe test *
[06:53:08] [Server thread/INFO]: §7§oDeath actions (Send to everyone):
[06:53:08] [Server thread/INFO]: §7§oJoin actions (Send to everyone):
[06:53:08] [Server thread/INFO]: §7§oKill entity actions (Send to everyone):
[06:53:08] [Server thread/INFO]: §7§oKill player actions (Send to everyone):
[06:53:08] [Server thread/INFO]: §7§oLeave actions:

**Comment by ghost** [comment]
everything is working thank you only it seems that the commands for events are not working .. example : "actions": [
            "Goodbye ${player}!",
            "/say Hope to see you soon ${player}"
        ],
makes the /say not appear as a command, but as plain text in the chat.

**Comment by IotaBread** [comment]
Since some commands may have unintended effects when testing, they are printed instead of executed. Although I should probably add a prefix when printing the commands

**Comment by ghost** [comment]
and last question... would it be possible to add first_join on server events?

**Comment by IotaBread** [comment]
Yes, it should be fairly easy to add it

**Comment by IotaBread** [comment]
Done in 2.1.2

**Comment by ghost** [comment]
hi i testing commands on first join event

this command work fine : 
 "/give ${player} golden_hoe 1"
but complex command like this crash server for syntax error in json file:
 "/replaceitem entity ${player} slot.hotbar.8 golden_hoe{display:{Name:'[{"text":"Ochrana pozemku","italic":false,"color":"gold"}]',Lore:['[{"text":"1 krok","italic":false,"color":"gray"},{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"Pravým klikni na","italic":false,"color":"dark_gray"}]','[{"text":"protilehlé rohy pozemku","italic":false,"color":"dark_gray"},{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"2 krok","italic":false,"color":"gray"},{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"Nastavení ","italic":false,"color":"dark_gray"},{"text":"/flan menu","color":"yellow"}]']}} 1"

where can be problem ?

**Comment by ghost** [comment]
same problem with give command

This work fine:
"/give ${player} golden_hoe 1"

Json syntax error:
"/give ${player} golden_hoe{display:{Name:'[{"text":"Ochrana pozemku","italic":false,"color":"gold"}]',Lore:['[{"text":"Popis funkce: ","italic":false,"color":"dark_gray"},{"text":"brzy bude xD","color":"yellow"}]']}} 1"

**Comment by ghost** [comment]
you can send me your pyapal I'd be happy to pay you at least for your efforts so far

**Comment by IotaBread** [comment]
Looks like you have unescaped double quotes. You have to escape the double quotes of the command with a backslashes, like this `\"text here\"`.

You can find my paypal.me link in [my website](https://bymartrixx.me) :)

**Comment by ghost** [comment]
how do you mean?  like this:

**Comment by ghost** [comment]
`\"/give ${player} golden_hoe 1\"`

**Comment by IotaBread** [comment]
I meant like this `"/give ${player} golden_hoe{display:{Name:\"[{\"text\":\"Ochrana pozemku\", \"italic\":false, \"color\":\"gold\"}]\", Lore:[\"[{\"text\":\"Popis funkce: \", \"italic\":false, \"color\":\"dark_gray\"}, {\"text\":\"brzy bude xD\", \"color\":\"yellow\"}]\"]}} 1"`

Tysm for the donation btw :)

**Comment by ghost** [comment]
thank you it seems to work now it's just a bug somewhere in my command xD

[21:00:19] [Server thread/INFO]: Expected '}'
[21:00:19] [Server thread/INFO]: ...{Name:"[{"text":"Ochrana pozemku", "italic":false, "color":"gold"}]", Lore:["[{"text":"Popis funkce: ", "italic":false, "color":"dark_gray"}, {"text":"brzy bude xD", "color":"yellow"}]"]}} 1<--[HERE]

and one more question. can you think of a way to deactivate default minecraft messages like [21:00:19] [Server thread/INFO]: Portable111 joined the game .. and use only text from your mod ?

**Comment by ghost** [comment]
it's scary but I get the error [Server thread/INFO]: Expected '}' on all attempts to fix the command .. I'm not sure if the error is on my side or not

**Comment by IotaBread** [comment]
I think it's on your side. Let me check

**Comment by IotaBread** [comment]
`/give ${player} golden_hoe{display:{Name:'[{\"text\":\"Ochrana pozemku\",\"italic\":false,\"color\":\"gold\"}]',Lore:['[{\"text\":\"Popis funkce: \",\"italic\":false,\"color\":\"dark_gray\"},{\"text\":\"brzy bude xD\",\"color\":\"yellow\"}]']}} 1` should work. I think I'm going to add something about this in the README

**Comment by ghost** [comment]
I got it xD .. what about the question. do you know how to block the default minecraft messages during an event or add it to the mod as a true/false condition?

**Comment by IotaBread** [comment]
I think I'm going to add that feature on the next release

**Comment by PortableGames** [comment]
hello I am extremely satisfied with the mod ;) and I would recommend one more new feature, namely playerTimeOnServer event.. where you could set the time played on the server and then call the command.

if you add this event and you can disable the default minecraft votes then only with your mod you can build a complete server
