### ISSUE TITLE
Reload command not working?

### ISSUE THREAD

**Issue by VoidLock92** [ByMartrixx/player-events#8]
When I change the Welcome message in the config save it then reload in game with the reload command it does not show the new msg it still shows the old message. So I don't think the reload command is working as intended.

**To Reproduce**
1. Change the config print out.
2. Save the config
3. Use reload command in game
4. old message still shows and reload did not work.

**Expected behavior**
It should use the new config settings after a reload and not the old settings anymore.

Reload command bug only seems to be affecting the login msg. All other events work fine with a reload besides the login msg that one takes a reload to take effect.

**Comment by VoidLock92** [comment]
I also seems to be placing a 'A' where every color code is used.

For instance I have color code "§6 BlahBlah" and it will print "A BlahBlah" and BlahBlah will be gold like it should. So not sure why it is putting an A.
![image](https://user-images.githubusercontent.com/21327041/126884353-5dd4e431-7eec-409c-af0c-6f71bc11b44f.png)

**Comment by IotaBread** [comment]
Thanks for reporting this bug! I'll fix it as soon as possible

**Comment by IotaBread** [comment]
I have fixed the reload command. The `A` may be an encoding issue, does your config file use UTF-8?

**Comment by VoidLock92** [comment]
Hmm I am not to sure what it is using to be honest. I am just using whatever file it made for me. I open it with Notepad++

**Comment by IotaBread** [comment]
Does it appear if you change the `§` with `\u00a7`

**Comment by VoidLock92** [comment]
I will give it a try, I know I did try & also and that was the same also. But have not yet had a chance to try the code you sent.
